import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  bookSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Welcome',
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'The Robotic Nervous System',
        description: 'Master ROS 2 - the middleware that makes robots tick.',
        slug: '/module-1-ros2',
      },
      items: [
        {type: 'autogenerated', dirName: 'module-1-ros2'},
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Simulation',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'The Digital Twin',
        description: 'Build virtual worlds where your robot can fail safely.',
        slug: '/module-2-simulation',
      },
      items: [
        {type: 'autogenerated', dirName: 'module-2-simulation'},
      ],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'The AI-Robot Brain',
        description: 'Unleash GPU-powered perception and navigation.',
        slug: '/module-3-isaac',
      },
      items: [
        {type: 'autogenerated', dirName: 'module-3-isaac'},
      ],
    },
    {
      type: 'category',
      label: 'Module 4: VLA',
      collapsible: true,
      collapsed: true,
      link: {
        type: 'generated-index',
        title: 'Vision-Language-Action',
        description: 'Where LLMs meet real-world robotics.',
        slug: '/module-4-vla',
      },
      items: [
        {type: 'autogenerated', dirName: 'module-4-vla'},
      ],
    },
  ],
};

export default sidebars;
